### ISSUE TITLE
What does the $product variable do here?

### ISSUE THREAD

**Issue by seanvandermolen** [bootscore/bs-swiper#10]
https://github.com/bootscore/bs-swiper/blob/73466d3f10eb27bec6bee6d30a8dfeef6ee4c97b/templates/sc-swiper-card-product.php#L52

I'm getting Undefined variable $product errors when I use this template.

**Comment by crftwrk** [comment]
This is the default WooCommerce product loop, no modifications were made here. So, this is interesting.

- Have you enabled the WP debug mode? If yes, disable it.
- What happens when you delete `$product`?

**Comment by seanvandermolen** [comment]
Ah, I have WP debug mode on while I'm working on updates.  I should consider it a non-issue w/ that plugin?

**Comment by crftwrk** [comment]
> I should consider it a non-issue w/ that plugin?

No, it's not a serious bug which affects the plugin's functionality. Maybe you get this error because Swiper is inserted in a page (not WC page) and WC is not active there. You can ignore it.
