### ISSUE TITLE
Is it a bug when you click?

### ISSUE THREAD

**Issue by kumasansord** [bootscore/bs-swiper#13]
I have a question.
When I click the link on the tablet, it slides.
Can't you jump to the link when you click?

**Comment by crftwrk** [comment]
Thanks for reporting, this sounds like a bug in swiper.js. Can you please share a link to your swiper and which bS Swiper version do you use?

**Comment by kumasansord** [comment]
Thank you for your reply
The swiper link is https://bootscore.me/documentation/bs-swiper/
bS Swiper ver.5.1.0.4
Thank you

**Comment by crftwrk** [comment]
I can't reproduce this bug on bootscore.me site. However, there is a new release with updated swiper.js 8.3.2 https://github.com/bootscore/bs-swiper/releases/download/v5.1.0.5/bs-swiper-main.zip.

Please clear your browser cache or view in a private tab and let me know if that solved https://bootscore.me/documentation/bs-swiper/.

Thank you

**Comment by kumasansord** [comment]
I cached my browser but it doesn't improve. PCs and smartphones are okay, but only ipad and android tabred click the button and slide without jumping to the link and the card moves to the far left.

**Comment by crftwrk** [comment]
I triple checked this on different devices (even on iPad) but cannot reproduce this permanentely. It appears one time at Mac Safari but was gone when refreshing the page and never came back. The code itself looks good, so I guess there is something minor in swiper.js. 

So, what you can do: Please downgrade to an earlier version and check if bug is still there
https://github.com/bootscore/bs-swiper/releases/download/5.1.0.2/bs-swiper-main.zip

Simply use the plugin-uploader for downgrade. This version doesn‘t crash something on your site, it‘s just an earlier version of swiper.js.

Thank you for reporting.
