### ISSUE TITLE
Post page view problem

### ISSUE THREAD

**Issue by phrizm** [bootscore/bs-swiper#17]
Hello Basti, i would like to create this thread as discussion but idk how to.

I have installed this usefull plugin, but if you take a look into this post ive got some wired behavior.

fyi: im using swiper.min.js and min.css to call another function of the carousel sliders. and its pointing plugin directory. all works fine. if you dont mind i need your kind suggestion:

https://www.northwestalps.com/2022/09/18/componenti-sciolti/

Thanks a lot.

**Comment by crftwrk** [comment]
Hi,

you have installed a second `swiper-bundle.min.js` in your child? May I ask why, because this is already in the plugin?

I got this error in console:
```
Failed to load resource: the server responded with a status of 404 ()
```

BTW there is `WP Fastest Cache` plugin enabled on your site. Please disable plugin to check further.

**Comment by phrizm** [comment]
Ok, "facepalm". I found an issue - now i have to point plugins directory for min.js and min.css.
I have commented function with swiper that i already had, now its working well.
Sorry for inconvenience and thank you for your kind reply. 
Once again my bad.

**Comment by crftwrk** [comment]
👍
