### ISSUE TITLE
Swiper image slider

### ISSUE THREAD

**Issue by phrizm** [bootscore/bs-swiper#18]
Hello Basti,

you can sign this one as discussion since there is no issues with plugin. I have to say its work prettybwell actually!

at 26 september i had an issue with your plugin since i have additional swiper script.

This one that im using with your theme

https://wp-tutorials.tech/refine-wordpress/multiple-gallery-effects-with-swiper/

and its working flawlessly. You defently have to check this one, since author (Paul) is just a php god in person.

My question is: since i had no luck to combine your plugin with this particular script, even if i pointed script to plugin folder and viceversa.. is there any way to combine em? Since im pretty unexperinced. maybe im missing something, im also pasted enqueue of plugin main.php into script enqueue the same exact folder.

Maybe im a bit unclear. Can we use the same swiper version with the same css file for cusfomizzation?

Im asking you because i think this particular gallery function is missing in bs pluins. There is a file link, but Pauls version can be deeply customized, and maybe you can grab it and rework it in bs way. 

Thank you for your attention. 😀

**Comment by crftwrk** [comment]
Hi phrizm,

of course, it should be possible to use plugins swiper styles and js. I suggest that you publish your child here in a GitHub repo, so I can check what's wrong.

**Comment by phrizm** [comment]
https://drive.google.com/drive/folders/1FJ6sbIyBORz3Y8vUn0pBq9HDKVGmwODG

**Comment by phrizm** [comment]
Thank you so much for this. This actually was a headache for me over 1 week.

**Comment by crftwrk** [comment]
How do I create a gallery in backend?

**Comment by phrizm** [comment]
add gallery with this class

swiper-gallery swiper-mode-coverflow swiper-navigation swiper-pagination

**Comment by crftwrk** [comment]
Can you please delete all stuff in child that is not related to the gallery and send again? So, just a blank child only with swiper gallery.

**Comment by phrizm** [comment]
https://drive.google.com/drive/folders/1kYZIc-2VtomGbQvDG_pafzXwsIqBge0Y?usp=sharing 

Here we go

**Comment by crftwrk** [comment]
Can you give me some more examples how to create galleries?

`swiper-gallery swiper-mode-coverflow swiper-navigation swiper-pagination`

**Comment by phrizm** [comment]
Yes, 

![image](https://user-images.githubusercontent.com/56654610/194038643-1ca0a0f3-7344-4adf-89f9-ed6c34561829.png)


Just add a regular gallery to you post page, then add css calss to whole gallery 

swiper-gallery swiper-mode-coverflow swiper-navigation swiper-pagination


More on docs here: https://wp-tutorials.tech/refine-wordpress/multiple-gallery-effects-with-swiper/

**Comment by crftwrk** [comment]
Please add just 5-6 example classes you want to use here, thank you ;-)

**Comment by phrizm** [comment]
Ah xD 

1 - Vertical
2 -  Coverflow
3 - Scrollbar
4 - Pagination progress
5 - Pagination dynamic 
6 - Pagination

I think those are most widely used ones
I hope that the final user can add more.

**Comment by crftwrk** [comment]
No, I mean complete class examples like this:

- `swiper-gallery swiper-mode-coverflow swiper-navigation swiper-pagination`
- `swiper-gallery swiper-mode-X swiper-navigation swiper-pagination`
- ...

All modes.

**Comment by phrizm** [comment]
`swiper-gallery swiper-mode-coverflow swiper-navigation swiper-pagination`
`swiper-gallery swiper-mode-vertical swiper-navigation swiper-pagination`
`swiper-gallery swiper-mode-scrollbar swiper-navigation swiper-pagination`
`swiper-gallery swiper-mode-pagination-progress swiper-navigation swiper-pagination`
`swiper-gallery swiper-mode-pagination-dynamic swiper-navigation swiper-pagination`
`swiper-gallery swiper-mode-pagination swiper-navigation swiper-pagination`

If i understood right

**Comment by crftwrk** [comment]
The gallery is very cool. I moved this out of the theme and created a plugin https://github.com/crftwrk/bs-swiper-gallery instead to make it reusable.

 **Before installing the plugin, you must remove all gallery files and functions in your child or start with a fresh child**.

Demo: https://dev.bootscore.me/plugins/bs-swiper/

Plugin uses the existing bS Swiper `swiper-bundle.min.js` and `swiper-bundle.min.css`.

### Available classes

- `swiper-gallery swiper-mode-coverflow swiper-navigation swiper-pagination`
- `swiper-gallery swiper-mode-cards swiper-navigation swiper-pagination`
- `swiper-gallery swiper-mode-cube swiper-navigation swiper-pagination`
- `swiper-gallery swiper-mode-slide swiper-navigation swiper-pagination`
- `swiper-gallery swiper-mode-fade swiper-navigation swiper-pagination`

More can created in [main.php](https://github.com/crftwrk/bs-swiper-gallery/blob/main/main.php) in line `89`

**Comment by phrizm** [comment]
Thats looks sick yeah. You did a great job! im gonna test itbout now.
superr! Can wr credit pauls in some way btw? And another thing can i
suggest you some future improvements on existing things? Thanks a lot..

Il gio 6 ott 2022, 10:27 Basti ***@***.***> ha scritto:

**Comment by phrizm** [comment]
Quick fix for glightbox jumps on top of the page: 

https://github.com/biati-digital/glightbox/issues/22

**Comment by crftwrk** [comment]
Can you please fork the plugin and create a PR? Thank you.

**Comment by phrizm** [comment]
PR stands for?
Github noob here.

**Comment by crftwrk** [comment]
Yes, looks good. Please PR ;-)
