### ISSUE TITLE
A way to disable update checker

### ISSUE THREAD

**Issue by szpak** [bootscore/bs-swiper#24]
We use the plugin in the environment with limited internet (output) connectivity. Occasionally in the logs there is:

> PHP Warning: The URL https://bootscore.me/wp-content/plugins/bs-swiper-main/update/plugin.json?installed_version=5.1.0.x&php=X.X.X&locale=xx_XX&checking_for_updates=1 does not point to a valid metadata file. WP HTTP Error: User has blocked requests through HTTP. in /var/www/.../bs-swiper/update/Puc/v4p11/UpdateChecker.php on line 430

It's not a big problem (they are quite rare), but maybe there could be some way to (optionally) disable the update checking? The plugins are updated separately.

**Comment by crftwrk** [comment]
Of course, no problem. Open `main.php` in plugin's root folder https://github.com/bootscore/bs-swiper/blob/main/main.php. There you will find this in lines `12` - `18`:

```php
// Update checker
require 'update/update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
  'https://bootscore.me/wp-content/plugins/bs-swiper-main/update/plugin.json',
  __FILE__, //Full path to the main plugin file or functions.php.
  'bs-swiper-main'
);
```

Comment or delete snippet to disable update checker. 

Does this help?

**Comment by szpak** [comment]
Thanks for your quick answer! Yes, that would help. However, that requires the plugin code manipulation. We could, in the (automated) build/compose process, patch that file (e.g. to comment it out), but it is somehow fragile for the further changes in the plugin :-/.

I wonder, if there could be (for example) checking for a variable defined, e.g. `BOOTSCORE_SWIPER_DISABLE_UPDATE_CKECKER` and if it is set to "true", the checker would not be included. I'm not from the PHP/WordPress community, so maybe there are some other "good practices" how the optional features could be disable without the code modification? WDYT?

**Comment by crftwrk** [comment]
Hmm, this seems as an edge case, because nearly nobody will use it. I either use the updater or remove it when I want to modify the plugin. For me it's not worth it, but if you want to code something like that, we're happy if you want to PR this. In this case, we must add it to all plugins.

**Comment by szpak** [comment]
If you think my case is the only one, then definitely, it will be easier to patch it locally on my side. Having some more people interested, it would be more justified to complicate the code.

Thanks for considering that change!
