### ISSUE TITLE
Undefined variable $product

### ISSUE THREAD

**Issue by binvoyons** [bootscore/bs-swiper#32]
Hello ! First of all, many thanks for all the work you do with bootScore and the plugins. You are doing a great job.

I was wondering if there was a possible bug with bs-swiper for WooCommerce products?

Here's what's returned when I put in the following shortcode:

`[bs-swiper-card-product category="marinades élémentaires" order="DESC" orderby="date" posts="6"]
`

<img width="841" alt="Capture d’écran, le 2023-07-15 à 15 44 04" src="https://github.com/bootscore/bs-swiper/assets/65147876/47ee4051-ebc6-4d03-8f1d-7c48fe62e4ab">

It works fine for pages and articles shortcodes. This error only occurs for product shortcodes.

I'm on a fresh bootScore install using the child theme.

Thank you very much for your help!

**Comment by crftwrk** [comment]
Hi,

thank you for reporting, this will be fixed by the next release.

However, it seems that you have set the `WP_DEBUG` to `true` in your `wp-config.php`. If so, set this to `false` and ignore errorr.

**Comment by binvoyons** [comment]
Great! Thank you :)
