### ISSUE TITLE
WP Plugin stop working when upgrade to 5.3.1

### ISSUE THREAD

**Issue by juanecl** [bootscore/bs-swiper#43]
Fatal error: Uncaught Error: Class "Puc_v4_Factory" not found in /wp-content/plugins/bs-swiper-main/main.php:21 Stack trace: #0 /wp-admin/includes/plugin.php(2318): include_once() #1 /wp-admin/plugins.php(192): plugin_sandbox_scrape('bs-swiper-main/...') #2 {main} thrown in /wp-content/plugins/bs-swiper-main/main.php on line 21

**Comment by crftwrk** [comment]
Hmm, usually there is no issue with automatic updates. However, please download https://github.com/bootscore/bs-swiper/releases/download/v5.3.1/bs-swiper-main.zip file directly and update plugin manually in backend.

**Comment by crftwrk** [comment]
Thanks for reporting. https://github.com/bootscore/bs-swiper/pull/47 will fix that.
