### ISSUE TITLE
Critical Error on line 21 in main.php - Puc_v4_Factory' not found in 

### ISSUE THREAD

**Issue by stuffthatspins** [bootscore/bs-swiper#44]
Opened our project this morning and I was getting a critical error:

 error log:
  thrown in /home/customer/www/igi.pixaura.com/public_html/wp-content/plugins/bs-swiper-main/main.php on line 21
[27-Aug-2023 15:01:19 UTC] PHP Fatal error:  Uncaught Error: Class 'Puc_v4_Factory' not found in /home/customer/www/igi.pixaura.  
  LINE 21:
  
  $myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(

commented out and the plugin works. 

// $myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
//   'https://bootscore.me/wp-content/plugins/bs-swiper-main/update/plugin.json',
//   __FILE__, //Full path to the main plugin file or functions.php.
//   'bs-swiper-main'
// );

**Comment by stuffthatspins** [comment]
this is happening on every one of our sites that use the bs-swiper plugin.

**Comment by crftwrk** [comment]
Thanks for reporting. https://github.com/bootscore/bs-swiper/pull/47 will fix that.
