### ISSUE TITLE
Way to slow down the slides

### ISSUE THREAD

**Issue by artinflight** [bootscore/bs-swiper#7]
Thank you for this great plugin for Bootscore! Made it very easy to install a post hero slider.

I'm wondering if there's a non-minified version of the JS available? I'm trying to slow down the slide speeds and I can't find the control in the init file.  

Also, I noticed in another thread that you recommend deleting the 'update' folder to stop the plugin from updating, I tried this and received a fatal Wordpress error until I re-uploaded the folder.

**Comment by crftwrk** [comment]
Thank you!

First, simply deactivate the update checker. Open `main.php` and go to lines `12` to `18`. There you will find this:

```php
// Update checker
require 'update/update-checker.php';
$myUpdateChecker = Puc_v4_Factory::buildUpdateChecker(
	'https://bootscore.me/wp-content/plugins/bs-swiper-main/update/plugin.json',
	__FILE__, //Full path to the main plugin file or functions.php.
	'bs-swiper-main'
);
```

Delete it.

Second, the speed is an option, which the hero-slider does not have by default but fade-slider uses it: `speed: 1500,` in `swiper-init.js` line `87`.

Just add `speed: 5000,` to hero-sliders options in line `53`. For example:

```js
...

/* Options */
speed: 5000,
slidesPerView: 1,
loop: true,

...
```

Speed is now 5 seconds.

Solved?

**Comment by artinflight** [comment]
Solved!! Thank you so much!
