### ISSUE TITLE
Custom Swiper settings

### ISSUE THREAD

**Issue by finalwebsites** [bootscore/bs-swiper#82]
Hi,

I need to change the values inside the swiper-init.js file. 
What is the best way to do this?
un-enqueue the plugin version and enqueue my own one?

**Comment by crftwrk** [comment]
Hello

> un-enqueue the plugin version and enqueue my own one?

Yes, that is the only way. Please check https://github.com/orgs/bootscore/discussions/768#discussioncomment-9415907 for explanation and example to enqueue own swiper-init with correct priority.

Does this clear this up?

Close this issue now because it has been already discussed.
